### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by NeferTiyi** [sybrenstuvel/flickrapi#106]
Is there a way to work with collections (getTree and getInfo) through flickrapi ? 
If not, is this something that will be possible at some point ?

**Comment by sybrenstuvel** [comment]
Is there any reason why it wouldn't work?

**Comment by NeferTiyi** [comment]
Ah ! My bad, sorry. I've been unsuccessfully trying to use this for days, but now everything seems ok... Probably a typo on my side...
