### ISSUE TITLE
license tag is not working

### ISSUE THREAD

**Issue by ppgiannak** [sybrenstuvel/flickrapi#108]
I am trying to avoid downloading non CC licensed photos with search, but no matter what i set the license parameter, it still gives me images with license id 0 (which refers to  'all rights reserved' license).
Has anyone else experienced the same problem?

Here's an example: 
`
search = flickr.photos.search(api_key=api_key, text='city', licence='2', sort='relevance', media='photos',per_page=500, page=1)
`
This retrieves images with all sorts of license IDs, e.g. 0, 2, 4..

**Comment by sybrenstuvel** [comment]
That's probably because the parameter is named after the noun, `license`, and not the verb, `licence`.
