### ISSUE TITLE
Wrong type for access_level

### ISSUE THREAD

**Issue by sybrenstuvel** [sybrenstuvel/flickrapi#63]
Originally reported by: **zaurky (Bitbucket: [zaurky](http://bitbucket.org/zaurky), GitHub: [zaurky](http://github.com/zaurky))**

----------------------------------------

In my env : 

  * python 2.7.3
  * flickrapi 2.1.2

access_level is a six.string_types (str) not an unicode.

Else I get :
```AssertionError: access_level should be unicode text, is <type 'str'>```

----------------------------------------
- Bitbucket: https://bitbucket.org/sybren/flickrapi/issue/63

**Comment by mthu** [comment]
Default arg value in 
auth.py:FlickrAccessToken.auth_url(self, perms='read')
and similar methods, causes an error when no argument is specified (Python 2.x). Shouldn't be there some Six magic?

**Comment by sybrenstuvel** [comment]
Yes, that default should indeed be fixed.

**Comment by sybrenstuvel** [comment]
Solved by @inirudebwoy in 622063463dafa7311b05873758b4321bd4690f6b
