### ISSUE TITLE
Make flickrapi token storage directory configurable (was: [Errno 13] Permission denied: '/.flickr')

### ISSUE THREAD

**Issue by lahdo** [sybrenstuvel/flickrapi#68]
I am receiving this error after deploying my django project on AWS. Why this lib is trying to create .flickr folder in /home/{username} ?

**Comment by lahdo** [comment]
Ok - now I understand. It needs this folder to store the token. We can disable storing by setting  store_token to false.        

flickr = flickrapi.FlickrAPI(self.KEY, self.SECRET, format='parsed-json', store_token=False)

Anyway I think location of this folder should be configurable.

**Comment by sybrenstuvel** [comment]
We can make the token cache directory configurable.

**Comment by hunterji** [comment]
I'd appreciate this change as well.

**Comment by sybrenstuvel** [comment]
Released as part of version-2.2
