### ISSUE TITLE
flickrapi.exceptions.FlickrError: Error: 112: Method "flickr.get.token.part.one" not found

### ISSUE THREAD

**Issue by zoeyun** [sybrenstuvel/flickrapi#69]
I do just like "https://stuvel.eu/flickrapi-doc/3-auth.html#token-handling-in-web-applications"  documents tells.
But when I run "

flickr = flickrapi.FlickrAPI(api_key, api_secret, cache=True)

flickr.token.path = '/tmp/flickrtokens'  
(token, frob) = flickr.get_token_part_one(perms='write')
if not token: 
    raw_input("Press ENTER after you authorized this program")
print token "

I got error like this:

File "/home/zoe/anaconda2/lib/python2.7/site-packages/flickrapi-2.1.2-py2.7.egg/flickrapi/core.py", line 283, in parse_etree
flickrapi.exceptions.FlickrError: Error: 112: Method "flickr.get.token.part.one" not found

Help me please!

**Comment by sybrenstuvel** [comment]
That example is obsolete, and I've removed it. At this moment you can't control the location of the auth token database. The easiest way to authenticate is this:

```python
import flickrapi

api_key = u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
api_secret = u'YYYYYYYYYYYYYYYY'

flickr = flickrapi.FlickrAPI(api_key, api_secret)
flickr.authenticate_via_browser(perms=u'write')
```

You seem to be using the old Python 2.7, so please use Unicode strings everywhere (`u'like this'`).
