### ISSUE TITLE
Unicode not really working in non-browser auth

### ISSUE THREAD

**Issue by kutysam** [sybrenstuvel/flickrapi#77]
...
verifier = unicode(raw_input('Please key in your verifier code: '))
flickr.get_access_token(verifier)
...

Error: AssertionError: access_level should be unicode text, is <type 'str'>

My access code was: 903-267-423

**Comment by kutysam** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=111103

My bad. I didn't place unicode for my 'delete' in perms.
i.e. u'delete'

**Comment by sybrenstuvel** [comment]
The `u''` prefix is only necessary for the soon-obsolete Python 2. Version 2.7.3 (as described in the forum topic you linked) is almost 5 years old. Maybe consider upgrading to a recent version?

**Comment by kutysam** [comment]
I was trying to use python for google photos as i wanted the 'free' photo upload feature.
https://developers.google.com/picasa-web/docs/1.0/developers_guide_python
However, they only seem to support 2.7 and I gave up trying to authenticate using their tools as alot of picasa web apis have died.

That's why i moved onwards to flickr and used your tool which is really awesome!
And yup, I shoulda used python 3 instead haha.

Thanks!
