### ISSUE TITLE
Authentication via browser not being triggered

### ISSUE THREAD

**Issue by atif93** [sybrenstuvel/flickrapi#79]
I have a simple python program for downloading files from Flickr accounts.
The public downloads happen perfectly but for private files I'm using 
`flickr.authenticate_via_browser(perms='read')`
which is not triggering the browser to open. The execution of the python program doesn't stop but no private files are downloaded.

**Comment by sybrenstuvel** [comment]
Please include a minimal example that shows the problem.

**Comment by atif93** [comment]
Okay I found out the problem. 
When any Flickr user account has authorized the app, the browser authentication is not triggering (reason I think is that the token is saved in cache). 
So, is there a way to have the browser authentication trigger the opening of browser by bypassing the cache check (because the token is different for different accounts)?

**Comment by sybrenstuvel** [comment]
The default behaviour is to expect that the user of you application is the same as the user who is currently logged in on the system. If you want to support multiple Flickr users who all use your application while logged in on the same machine on the same user account, you need to take some extra steps. I would suggest reading the section [Authentication and Authorization](https://stuvel.eu/flickrapi-doc/3-auth.html) of the documentation.

**Comment by atif93** [comment]
passing `username` parameter to the `FlickrAPI` constructor did the trick.
Now tokens for different users are not mixed up in the cache.

**Comment by sybrenstuvel** [comment]
Thanks for posting an update, I'm glad it worked out for you.
