### ISSUE TITLE
Feature request: work with Flickr albums

### ISSUE THREAD

**Issue by patrick-brian-mooney** [sybrenstuvel/flickrapi#83]
I think that the title says it all: basically, I'd like to be able to create albums, upload photos into a specific album, and delete and rename albums. 

There is apparently some information available on using the Flickr API for this: http://stackoverflow.com/questions/2058025/adding-a-photo-collection-using-the-flickr-api

Anyway, it would be quite helpful if available. Many thanks.

**Comment by sybrenstuvel** [comment]
This is already possible. The Python FlickrAPI library is made in such a dynamic way, that it doesn't have to be changed to support new functions. You can just call them.

**Comment by patrick-brian-mooney** [comment]
Ah! Thank you so much!

And thank you for an excellent package with very well-written documentation. It's much appreciated.
