### ISSUE TITLE
Dates, text and tags parameters don't work on search

### ISSUE THREAD

**Issue by MarioMacedo22** [sybrenstuvel/flickrapi#88]
The dates parameters (min_upload_date, max_upload_date, min_taken_date, max_taken_date) does not work.
I'm using  this 
`photos = flickr.photos.search(text='portugal', min_taken_date = "2015-01-01", max_taken_date  = "2016-12-31")`
 and are returned posts that were made in 2017 and are with subjects very different than Portugal.

**Comment by sybrenstuvel** [comment]
Have you tested the same query on Flickr's API explorer to see what's the result? https://www.flickr.com/services/api/explore/flickr.photos.search

That will tell you if it's an issue with Flickr itself or with the software.

**Comment by MarioMacedo22** [comment]
You're right, sorry my bad.
