### ISSUE TITLE
`method_name` parameter name conflict

### ISSUE THREAD

**Issue by codebicycle** [sybrenstuvel/flickrapi#90]
`flickr.reflection.getMethodInfo` requires `method_name` as argument but clashes with `method_name` parameter from `do_flickr_call()` method signature: `do_flickr_call(self, method_name, timeout=None, **kwargs)`.

    >>> flickr.reflection.getMethodInfo(method_name='flickr.test.echo')
    TypeError: do_flickr_call() got multiple values for argument 'method_name'

**Comment by sybrenstuvel** [comment]
Fixed by merging PR #91
