### ISSUE TITLE
Was anyone able to use fileobj on flickr.upload with FileWithCallback?

### ISSUE THREAD

**Issue by oPromessa** [sybrenstuvel/flickrapi#94]
Was anyone able to use fileobj on flickr.upload with FileWithCallback?

Based on the example [flickr-upload](https://stuvel.eu/flickrapi-doc/4-uploading.html#flickr-upload)...
- I've copied all the sample code
- I've defined params... (code below)
- I'm getting this error

> Uploading /volume1/photo/Test/0000-00-00 Teste/IMG_0000.jpg...
> setName: 0000-00-00 Teste
> Traceback (most recent call last):
>   File "./uploadr.py", line 1486, in <module>
>     flick.upload()
>   File "./uploadr.py", line 487, in upload
>     success = self.uploadFile(file)
>   File "./uploadr.py", line 677, in uploadFile
>     uploadResp = nuflickr.upload( params )
>   File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 494, in upload
>   File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 544, in _upload_to_form
>   File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 399, in _wrap_in_parser
>   File "build/bdist.linux-x86_64/egg/flickrapi/auth.py", line 281, in do_upload
>   File "/usr/lib/python2.7/posixpath.py", line 114, in basename
>     i = p.rfind('/') + 1
> AttributeError: 'dict' object has no attribute 'rfind'

Code I have:
```
params = {}
params['filename'] = file
params['fileobj'] = FileWithCallback( params['filename'], self.callback)
params['title']=str(FLICKR["title"])
params['description']=str(FLICKR["description"])
params['is_public']=str(FLICKR["is_public"])
params['is_friend']=str(FLICKR["is_friend"])
params['is_family']=str(FLICKR["is_family"])

uploadResp = nuflickr.upload( params )
```

Any help is welcome! Thank you all!

**Comment by sybrenstuvel** [comment]
`params['filename'] = file` assigns the built-in name `file`. If you're reassigning built-in names, please post complete code to make this clear. Also `self.callback` is undefined.

**Comment by oPromessa** [comment]
Thanks for the support.

I attach the full code. 
[uploadr.py.txt](https://github.com/sybrenstuvel/flickrapi/files/1404031/uploadr.py.txt)

It's work in progress migrating [trickortweak/flickr-uploader](https://github.com/trickortweak/flickr-uploader) to make use of flickrapi and the new OAUTH method.

I include an updated output aligned with the code (credentials masked):
```
--------- Start time: Sat Oct 21 13:00:08 2017 ---------
False
Token obtained:  FlickrAccessToken(token=XXXXXXXXXXXX-XXXXXXXXXXX, fullname=XXXX XXXXXXX, username=XXXXXX, user_nsid=XXXXXXXX)
Setting up the database: ./flickrdb
Completed database setup
*****Removing empty Sets from DB*****
*****Completed removing empty Sets from DB*****
*****Adding Flickr Sets to DB*****
<rsp stat="ok">
<photosets cancreate="1" page="1" pages="1" perpage="0" total="0" />
</rsp>
*****Completed adding Flickr Sets to DB*****
*****Uploading files*****
Found 3 files
Uploading /volume1/photo/Test/0000-00-00 Teste/IMG_0000.jpg...
setName: 0000-00-00 Teste
Traceback (most recent call last):
  File "./uploadr.py", line 1496, in <module>
    flick.upload()
  File "./uploadr.py", line 487, in upload
    success = self.uploadFile(file)
  File "./uploadr.py", line 677, in uploadFile
    uploadResp = nuflickr.upload( params )
  File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 494, in upload
  File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 544, in _upload_to_form
  File "build/bdist.linux-x86_64/egg/flickrapi/core.py", line 399, in _wrap_in_parser
  File "build/bdist.linux-x86_64/egg/flickrapi/auth.py", line 281, in do_upload
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'dict' object has no attribute 'rfind'
```

Thanks for your support.

**Comment by sybrenstuvel** [comment]
The code is hard to read, with very long lines, not being PEP-8 compliant, assigning to built-in Python names, and functions with heavily indented nested functions, loops, and conditionals. I would seriously consider refactoring the code to simplify it.

You're passing `params` (which is a dict) as the first parameter of `FlickrAPI.upload()`, while that parameter is `filename` (which should be a string). You probably can fix this using `nuflickr.upload(**params)`, but, instead of using a dict `params`, why not keep things simple, and just pass the parameters directly?

**Comment by bigzdog** [comment]
@oPromessa I am using a different project that was built on the trickortweak code to use the new OAUTH method. See here https://github.com/alfem/synology-flickr-folder-uploader/blob/master/flickr-folder-uploader.py

It seems to work fine outside of every 2-3 days I must reauthenticate with OAUTH with a new access code? Not sure why that is happening.

**Comment by sybrenstuvel** [comment]
@bigzdog please stay on topic for this particular issue.

**Comment by oPromessa** [comment]
True... code surely needs refactoring... work in progress :)

I was using params based on the flickrapi documentation.
*SUPER* from your suggestion and with the following code it is now working!!! Thanks a lot!!!

```
uploadResp = nuflickr.upload( filename = file, \
                                                  fileobj = FileWithCallback( file, callback), \
                                                  title=str(FLICKR["title"]), \
                                                  description=str(FLICKR["description"]), \
                                                  tags='{} checksum:{}'.format(FLICKR["tags"], file_checksum).replace(',', ''), \
                                                  is_public=str(FLICKR["is_public"]), \
                                                  is_family=str(FLICKR["is_family"]), \
                                                  is_friend=str(FLICKR["is_friend"]) )
```
